// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoManager_Marwa.Models.RestosModel;

#nullable disable

namespace RestoManager_Marwa.Migrations
{
    [DbContext(typeof(RestosDbContext))]
    [Migration("20250510010242_SecondCreate")]
    partial class SecondCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestoManager_Marwa.Models.RestosModel.Avis", b =>
                {
                    b.Property<int>("CodeAvis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeAvis"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NomPersonne")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.Property<string>("NumResto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CodeAvis");

                    b.HasIndex("NumResto");

                    b.ToTable("TAvis", "admin");
                });

            modelBuilder.Entity("RestoManager_Marwa.Models.RestosModel.Proprietaire", b =>
                {
                    b.Property<string>("Gsm")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("GsmProp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EmailProp");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NomProp");

                    b.HasKey("Gsm");

                    b.ToTable("TProprietaire", "resto");
                });

            modelBuilder.Entity("RestoManager_Marwa.Models.RestosModel.Restaurant", b =>
                {
                    b.Property<string>("CodeResto")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomResto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumProp")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Tunisienne")
                        .HasColumnName("SpecResto");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("TelResto");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("VilleResto");

                    b.HasKey("CodeResto");

                    b.HasIndex("NumProp");

                    b.ToTable("TRestaurant", "resto");
                });

            modelBuilder.Entity("RestoManager_Marwa.Models.RestosModel.Avis", b =>
                {
                    b.HasOne("RestoManager_Marwa.Models.RestosModel.Restaurant", "LeResto")
                        .WithMany("LesAvis")
                        .HasForeignKey("NumResto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Relation_Resto_Avis");

                    b.Navigation("LeResto");
                });

            modelBuilder.Entity("RestoManager_Marwa.Models.RestosModel.Restaurant", b =>
                {
                    b.HasOne("RestoManager_Marwa.Models.RestosModel.Proprietaire", "LeProprio")
                        .WithMany("LesRestos")
                        .HasForeignKey("NumProp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Relation_Proprio_Restos");

                    b.Navigation("LeProprio");
                });

            modelBuilder.Entity("RestoManager_Marwa.Models.RestosModel.Proprietaire", b =>
                {
                    b.Navigation("LesRestos");
                });

            modelBuilder.Entity("RestoManager_Marwa.Models.RestosModel.Restaurant", b =>
                {
                    b.Navigation("LesAvis");
                });
#pragma warning restore 612, 618
        }
    }
}
